### ISSUE TITLE
Staging Serverに自動デプロイしたい

### ISSUE THREAD

**Issue by TinyKitten** [TeamKitten/NoteNote#17]
VPSで今ホストしてるので単純にdevelopにマージされたらVPSにSSH接続してDocker buildするだけでよさげ

**Comment by TinyKitten** [comment]
それか、dockerをprivateにホストしてpullするだけとか。

**Comment by TinyKitten** [comment]
Actionsのほうでdockerイメージビルドしてgithubのpackagesに一旦上げた方が取り回しがいいと思うのでactionsでdocker buildしてpackagesにpushしてVPSの方からpullしよう

**Comment by makotia** [comment]
close 忘れ？

**Comment by TinyKitten** [comment]
ZenHubの方見れるかわからないけど見るとDoneに入ってる
