### ISSUE TITLE
アクセスしたノートが存在しない場合通知するようにする

### ISSUE THREAD

**Issue by TinyKitten** [TeamKitten/NoteNote#84]
## 🚀 Feature Request
アクセスしたノートが存在しない場合何も表示されないので分かりづらい

## Example
トーストか何かで削除された旨を通知する

**Comment by makotia** [comment]
Editor のところに 404 の旨を表記してもいいのかも？
トーストだと通知出てきた後どうするって感じだし

**Comment by nirsmmy** [comment]
ルートに飛ばしてから通知出すのもあり
