### ISSUE TITLE
画面の幅が狭いとタイトルが埋まる

### ISSUE THREAD

**Issue by makotia** [TeamKitten/NoteNote#98]
### 🐛 Summary
埋まる
### Expected behavior
埋まらない
### Screenshot
![image](https://user-images.githubusercontent.com/22451396/87851519-72385c00-c934-11ea-96e6-9fe1ae4a1b28.png)

### Version
0.1
### Build Number
20200718.092149

**Comment by TinyKitten** [comment]
#135 でおそらく解決
